# Generated by Django 3.0.5 on 2020-06-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_ride', '0002_auto_20200601_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettransportrequest',
            old_name='flexible',
            new_name='is_flexible',
        ),
        migrations.RenameField(
            model_name='riderequest',
            old_name='flexible',
            new_name='is_flexible',
        ),
        migrations.RenameField(
            model_name='shareride',
            old_name='flexible',
            new_name='is_flexible',
        ),
        migrations.RenameField(
            model_name='sharetravelinfo',
            old_name='flexible',
            new_name='is_flexible',
        ),
    ]
